# This script is run via Buildkite's scheduled jobs feature.
#
# It's meant to rebuild various CI caches on a periodic async basis, so as
# not to waste time on every CI job updating the cache.

# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/bash-cache#2.9.0
    - automattic/git-s3-cache#v1.1.3:
        bucket: "a8c-repo-mirrors"
        repo: "automattic/simplenote-ios/"
  # Common environment values to use with the `env` key.
  - &common_env
    IMAGE_ID: xcode-14.0.1

steps:

  #################
  # Build the Git Repo cache
  #
  # Because this repo is so large, we periodically create a Git Mirror and copy it to S3,
  # from where it can be fetched by agents more quickly than from GitHub, and so that
  # agents then have less new commits to `git pull` by using that cache as starting point
  #################
  - label: ":git: Rebuild git cache"
    command: "cache_repo a8c-repo-mirrors"
    plugins: *common_plugins
    agents:
      queue: "default"
