# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

# Variables used in this pipeline are defined in `shared-pipeline-vars`, which is `source`'d before calling `buildkite-agent pipeline upload`

agents:
  queue: mac

env:
  IMAGE_ID: $IMAGE_ID

# This is the default pipeline – it will build and test the app
steps:

  #################
  # Run Unit Tests
  #################
  - label: "🔬 Build and Test"
    command: ".buildkite/commands/build-and-test.sh"
    plugins: [$CI_TOOLKIT_PLUGIN]
    artifact_paths:
      - "build/results/*"

  #################
  # Linters
  #################
  - label: "☢️ Danger - PR Check"
    command: danger
    key: danger
    if: "build.pull_request.id != null"
    retry:
      manual:
        permit_on_passed: true
    agents:
      queue: "linter"

  - label: ":swift: SwiftLint"
    command: swiftlint
    agents:
      queue: "linter"

  #################
  # Create Installable Build
  #################
  - label: "🛠 Installable Build"
    command: ".buildkite/commands/build-prototype.sh"
    plugins: [$CI_TOOLKIT_PLUGIN]
    if: "build.pull_request.id != null || build.pull_request.draft"
    artifact_paths:
      - "build/results/*"

  #################
  # UI Tests
  #################
  - label: "🔬 UI Test (Full)"
    command: ".buildkite/commands/build-and-ui-test.sh SimplenoteUITests 'iPhone SE (3rd generation)'"
    plugins: [$CI_TOOLKIT_PLUGIN]
    artifact_paths:
      - "build/results/*"
