# This is the default pipeline – it will build and test the app

agents:
  queue: mac

env:
  IMAGE_ID: $IMAGE_ID

steps:
  - label: 🔬 Build and Test
    command: .buildkite/commands/build-and-test.sh
    plugins: [$CI_TOOLKIT_PLUGIN]
    artifact_paths:
      - build/results/*

  - label: ":swift: SwiftLint"
    command: run_swiftlint --strict
    plugins: [$CI_TOOLKIT_PLUGIN]
    notify:
      - github_commit_status:
          context: SwiftLint
    agents:
      queue: default

  - label: 🛠 Installable Build
    command: .buildkite/commands/build-prototype.sh
    plugins: [$CI_TOOLKIT_PLUGIN]
    if: "build.pull_request.id != null || build.pull_request.draft"
    artifact_paths:
      - build/results/*

  - label: 🔬 UI Test (Full)
    command: .buildkite/commands/build-and-ui-test.sh SimplenoteUITests 'iPhone SE (3rd generation)'
    plugins: [$CI_TOOLKIT_PLUGIN]
    artifact_paths:
      - build/results/*
