# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/bash-cache#2.9.0
    - automattic/git-s3-cache#v1.1.3:
        bucket: "a8c-repo-mirrors"
        repo: "automattic/simplenote-ios/"
  # Common environment values to use with the `env` key.
  - &common_env
    IMAGE_ID: xcode-14.0.1

# This is the default pipeline – it will build and test the app
steps:

  #################
  # Run Unit Tests
  #################
  - label: "🔬 Build and Test"
    command: ".buildkite/commands/build-and-test.sh"
    env: *common_env
    plugins: *common_plugins
    artifact_paths:
      - "build/results/*"

  #################
  # Create Installable Build
  #################
  - label: "🛠 Installable Build"
    command: ".buildkite/commands/build-prototype.sh"
    env: *common_env
    plugins: *common_plugins
    if: "build.pull_request.id != null || build.pull_request.draft"
    artifact_paths:
      - "build/results/*"

  #################
  # UI Tests
  #################
  - label: "🔬 UI Test (Subset)"
    command: ".buildkite/commands/build-and-ui-test.sh SimplenoteUITests_Subset 'iPhone SE (3rd generation)'"
    env: *common_env
    plugins: *common_plugins
    artifact_paths:
      - "build/results/*"

  - block: "🔬 UI Test (Full)"
    prompt: "Run full set of UI tests (~33 min)?"
  - command: ".buildkite/commands/build-and-ui-test.sh SimplenoteUITests 'iPhone SE (3rd generation)'"
    env: *common_env
    plugins: *common_plugins
    artifact_paths:
      - "build/results/*"
