# This pipeline is meant to be run via the Buildkite API, and is only used for release builds

# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/a8c-ci-toolkit#3.0.1
  # Common environment values to use with the `env` key.
  - &common_env
    IMAGE_ID: xcode-15.1

steps:

  - label: ":testflight: Simplenote iOS Release Build (App Store Connect)"
    command: ".buildkite/commands/release-build.sh"
    priority: 1
    env: *common_env
    plugins: *common_plugins
    notify:
    - slack: "#build-and-ship"
