# This pipeline is meant to be run via the Buildkite API, and is only used for release builds

# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/bash-cache#2.9.0
    - automattic/git-s3-cache#v1.1.3:
        bucket: "a8c-repo-mirrors"
        repo: "automattic/simplenote-ios/"
  # Common environment values to use with the `env` key.
  - &common_env
    IMAGE_ID: xcode-14.0.1

steps:

  - label: ":testflight: Simplenote iOS Release Build (App Store Connect)"
    command: ".buildkite/commands/release-build.sh"
    env: *common_env
    plugins: *common_plugins
    notify:
    - slack: "#build-and-ship"
