# This pipeline is meant to be run via the Buildkite API, and is only used for release builds

# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/a8c-ci-toolkit#2.15.0
    - automattic/git-s3-cache#1.1.4:
        bucket: "a8c-repo-mirrors"
        repo: "automattic/simplenote-ios/"
  # Common environment values to use with the `env` key.
  - &common_env
    IMAGE_ID: xcode-14.2

steps:

  - label: ":testflight: Simplenote iOS Release Build (App Store Connect)"
    command: ".buildkite/commands/release-build.sh $BETA_RELEASE"
    priority: 1
    env: *common_env
    plugins: *common_plugins
    notify:
    - slack: "#build-and-ship"
