# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

# Variables used in this pipeline are defined in `shared-pipeline-vars`, which is `source`'d before calling `buildkite-agent pipeline upload`

agents:
  queue: mac

env:
  IMAGE_ID: $IMAGE_ID

steps:
  - label: ":testflight: Build Simplenote iOS for App Store Connect"
    key: testflight_build
    command: |
      checkout_release_branch $RELEASE_VERSION
      .buildkite/commands/release-build.sh
    priority: 1
    plugins: [$CI_TOOLKIT_PLUGIN]
    artifact_paths:
      - build/results/*.zip
      - build/results/*.ipa

  - label: ":testflight: Upload Simplenote iOS to App Store Connect"
    depends_on: testflight_build
    # This step does not only upload to ASC, but also create a GitHub release.
    # For that, it needs to be on the latest release branch commit, hence the checkout command
    command: |
      checkout_release_branch $RELEASE_VERSION
      .buildkite/commands/release-upload.sh $BETA_RELEASE
    priority: 1
    plugins: [$CI_TOOLKIT_PLUGIN]
    notify:
      - slack: "#build-and-ship"
