steps:
  - label: ":testflight: Simplenote iOS Release Build (App Store Connect)"
    command: .buildkite/commands/release-build.sh
    priority: 1
    env:
      IMAGE_ID: $IMAGE_ID
    agents:
      queue: mac
    plugins: [$CI_TOOLKIT_PLUGIN]
    notify:
    - slack: "#build-and-ship"
