# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

########################################
# App Metadata
########################################

# This folder has to include one folder for each language
screenshots_path "./screenshots/"
app_identifier "com.codality.NotationalFlow"

# Make sure to update these keys for a new version
app_version "4.41"

privacy_url({
  'default' => 'https://simplenote.com/privacy/',
})

copyright('2021 Automattic')

skip_binary_upload true
overwrite_screenshots true
phased_release true

# We are using the API key to upload the metadata to ASC via Deliver, but, as
# the tool reports:
#
# > [!] Precheck cannot check In-app purchases with the App Store Connect API
# > Key (yet). Exclude In-app purchases from precheck, disable the precheck step
# > in your build step, or use Apple ID login
#
# Simplenote iOS doesn't use IAPs, for the moment, so we can safely skip them.
precheck_include_in_app_purchases false
